// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package database

import (
	"time"
)

type Comments struct {
	ID               int64     `json:"id"`
	MovieID          string    `json:"movie_id"`
	CommentIpAddress string    `json:"comment_ip_address"`
	Comment          string    `json:"comment"`
	CreatedAt        time.Time `json:"created_at"`
}
