// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package database

import (
	"context"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comments, error)
	GetCommentNumber(ctx context.Context, movieID string) (int64, error)
	ListComments(ctx context.Context, arg ListCommentsParams) ([]Comments, error)
}

var _ Querier = (*Queries)(nil)
